apiVersion: v1
kind: Service
metadata:
  labels:
    name: go-proxy-service
  name: go-proxy-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      nodePort: 30511
      targetPort: 8888 # This must match `containerPort` for go-proxy in your deployment.yml
  selector:
     app: minikube-kafka-rest-deployment
